name: Base CI pipeline

on:
  push:
    branches: [master, develop]
  pull_request:
    branches:
      - master

jobs:
  format-lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier check
        run: |
          echo "Running Prettier to check for formatting issues..."
          npm run prettier:check

      - name: Run ESLint check
        run: |
          echo "Running ESLint to check for linting issues..."
          npm run lint

      - name: Run TypeScript compile check
        run: |
          echo "Running TypeScript compiler to check for type issues..."
          npx tsc --noEmit

      - name: Run API ENV variables tests
        env:
          USERNAME: ${{secrets.USERNAME}}
          PASSWORD: ${{secrets.PASSWORD}}
        run: |
          echo "Running ENV variable tests..."
          npx playwright test /HW_11/ /HW_12/ --workers=1

      - name: Set up Docker Compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: ./docker-compose.yaml
          up-flags: -d

      - name: Run local API test for empty array scenario
        run: npx playwright test tests/emptyArray.spec.ts  --workers=1

      - name: Run Playwright local API tests
        run: |
          echo "Running Playwright to execute local API tests..."
          npx playwright test tests/User.Api.spec.ts --workers=1

      - name: Run Playwright local loop API tests
        run: |
          echo "Running Playwright to execute local loop API tests..."
          npx playwright test tests/HW_14/apiLoop.spec.ts --workers=1

      - name: Run rest API tests
        run: |
          echo "Running Playwright to execute API tests..."
          npx playwright test tests/HW_09/ /HW_10/ --workers=1
